kind: Pod
apiVersion: v1
metadata: 
  name: label-pod
  labels:
    type: collective
    env: production
spec:
  containers:
  - image: aamirpinger/helloworld
    name: container1
    ports:
    - containerPort: 80   
