apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test-2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Mi
  hostPath:
    path: "/tmp/data1"
  persistentVolumeReclaimPolicy: Delete
