apiVersion: v1
kind: PersistentVolume
metadata:
  name: deployment-pv
  namespace: axiom
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /tmp
  persistentVolumeReclaimPolicy: Delete
