apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deployment-pvc
  namespace: axiom
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: ""
       
 
