apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: myrs
spec:
  replicas: 5
  selector:
    matchLabels:
      type: app
  template:
    metadata:
      labels:
        type: app
    spec:
      containers:
      - name: con1
        image: nginx
        ports:
        - containerPort: 80

      
