kind: PersistentVolume
apiVersion: v1
metadata:
  name: hostpath2
  labels:
    type: local
spec:
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteOnce
reclaimPolicy:
- Recycle
  hostPath:
    path: "/tmp/data1"
