apiVersion: v1
kind: Service
metadata:
  name: deploy-nps-roll
  namespace: axiom
spec:
  type: NodePort
  selector:
    type: frontend
    strategy: rolling
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30010
